---
driver_plugin: vagrant
platforms:
- name: centos
  driver_config:
    box: centos-6.3-x86_64
    box_url: http://engrepo.f4tech.com/vagrant/centos-6.3-x86_64.box
    require_chef_omnibus: 11.4.4
    customize:
      cpus: 1
      memory: 256
    network:
      - ["private_network", { ip: "10.0.2.15" }]
suites:
- name: default
  run_list:
    - recipe[grails]
    - recipe[minitest-handler]
